Calling `self.__init__()` now results in a nice error instead of a panic in the yul compilation stage.
